[package]
name = "labtyp"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["evidlabel"]
license = "MIT"
description = "A Typst package for labelling text and enabling json label extraction using typst query"
repository = "https://github.com/evidlabel/labtyp" # Optional, update if hosting on GitHub
keywords = ["headings", "labels", "footnotes", "metadata", "hyperlinks"]

[template]
path = "template"
entrypoint = "main.typ"
